### ISSUE TITLE
Print diagnostic metrics for fool-proofing purposes?

### ISSUE THREAD

**Issue by gnwong** [AFD-Illinois/kharma#19]
I just spent a long time diagnosing what I had thought was a library issue that was in fact an issue with my choice for meshblock size (I had designed the par file for a production run and then tried using it in a development queue).

If possible, it might be nice to explicitly run checks for various different bad choices a new user could accidentally make and then print information when the code first begins. 

This certainly isn't a critical issue, but it might help ease others into using the code.

Thoughts?

**Comment by c-prather** [comment]
This would be great to have.  KHARMA already guesses a lot of coordinate and meshblock parameters in "FixParameters" in kharma.cpp, adding a battery of basic checks there seems good.

That said, putting too many meshblocks on a rank shouldn't actually be terribly slow unless you run out of RAM; it's likely a bug with KHARMA or else Parthenon.  I'll try to repro in KHARMA and the Parthenon examples, and push upstream if needed.

**Comment by c-prather** [comment]
After running into something similar again myself, I've added some basic meshblock printing when `verbose >= 1` that should make this sort of thing easier to spot.  Parthenon also has warnings for AMR, where it's more common to unintentionally create a million meshblocks.

So, marking that #33 basically resolves this.  If there are common mis-configurations we can add special checks, but I prefer to trust and print rather than hand-hold.

**Comment by c-prather** [comment]
Closing since #33 is merged, so we now print meshblock counts.  I'd love to be able to back-of-the-envelope memory usage on SMR runs and warn users, but it's not very feasible. We could try to warn when there are more than a certain number of blocks per rank, but plenty of testing scenarios call for small e.g. 8x8 blocks to test for internal boundary effects...
FWIW in AMR, Parthenon has some basic warnings inherited from Athena when it looks like refinement might get out of hand.
