### ISSUE TITLE
Performance difference between drivers

### ISSUE THREAD

**Issue by vedantdhruv96** [AFD-Illinois/kharma#55]
I recently tested the performance of KHARMA's drivers (with the latest `stable` version following the #42 PR) on a single A100 on NCSA Delta. I found a significant enough difference - `imex` being faster than `kharma` - to open an issue. Perhaps this is anticipated due to a fundamental difference in the drivers, in which case this Issue can be closed as is. A closing comment that explains the difference would be appreciated.

A `288x128x128` torus problem with a single meshblock runs at 25.6M ZCPS on average with the `imex` driver and at 17.6M ZCPS on average with the `kharma` driver. FWIW, the relative difference in performance is also observed upon increasing the number of meshblocks.

**Comment by c-prather** [comment]
Neat! I expected there might be a small difference, as I've moved over the `imex` driver to using `MeshData` objects exclusively while I was bug-hunting.  Since it turned out not to help with the bug I postponed moving over the `kharma` driver to join it until all the tests were passing & such, and I could rewrite some functions to expect `MeshData`s to actually realize more of the speedup.

`MeshData` objects are packed over all blocks on a rank, and avoid unnecessary GPU kernel launches (at least, in places), so better performance with more meshblocks is definitely expected.  Better performance with one block is not, though -- I wonder if there's some more incidental difference that could be ported over to make the KHARMA driver faster (e.g. I pack slightly different variables for MPI, where I don't always need to...)
